services:
  backend:
    container_name: "chongkran-backend"
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    container_name: "chongkran-db"
    image: mongodb/mongodb-community-server:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
